Rem Script by SRIVENU KADIYALA - mail - srivenu@hotmail.com

advise				-	ad	adv
archive				-	ar	arc
ash				-	ah	ash
asm				-	as	asm
awr				-	aw	awr
background			-	bg	bgr
bind				-	bn	bnd
block				-	bk	blk
baseline			-	bl	bsl
buffer				-	bu	buf
cache				-	ca	cac
client	 			-	ci	cln
column				-	cl	col
compile				-	co	cpl
constraints			-	ct	con
costly				-	cs	cst
cpu				-	cp	cpu
current				-		cur
cursor				-	cr	csr
data				-	df	dat
database			-	db	dbs
datapump			-	dp	dpp
ddl				-	dl	ddl
dead				-	dd	ded
dependencies			-	dc	dep
destination			-	ds	dst
detail				-	dt	det
disk				-	dk	dsk
enqueue				-	eq	enq
event				-	ev	evt
extent				-	et	ext
execution			-	ex	exe
file				-	fi	fil
goldengate			-	gg	ggt
group				-	gr	grp
histograms			-	hg	hsg
history				-	hy	hsy
hot				-	ht	hot
indexes				-	in	ind
invalid				-	iv	inv
io				-	io	iop
job				-	jb	job
kill				-	ki	kil
large				-	lr	lrg
latch				-	la	lat
librarycache			-	li	lca
lob				-	lb	lob
lock				-	lk	lck
log				-	lg	log
materialized view		-	mv	mvw
memory				-	mm	mem
monitor				-	mn	mon
mutex				-	mu	mtx
new				-	ne	new
object				-	ob	obj
operations			-	op	ops
parallel execution		-	px	pax
parameter			-	pm	prm
parse				-	pa	prs
partition			-	pt	ptt
pga(memory)			-	py	pga
pin				-	pn	pin
plan				-	pl	pln
plsql				-		pls
privileges			-	pv	pvg
process				-	pr	prc
profile				-	pf	prf
program				-	pg	prg
queue				-	qu	que
rac				-	rc	rac
redo				-	rd	red
referential			-	rf	ref
rman				-	rm	rmn
row				-	rw	row
run/running			-	ru	run
segment				-	sg	seg
service				-	sv	svc
session 			-	se	ses
sequences			-	sc	seq
sharedpool			-	sr	spo
show				-	sh	sho
sort				-	so	sor
space				-	sp	spa
sql				-	sq	sql
standby				-	sb	stb
statistics			-	st	stt
synonyms			-	sm	syn
system 				-	sy	sys
table				-	tb	tab
tablespace			-	ts	tbs
temp				-	te	tmp
time				-	tm	tim
transaction			-	tx	trx
trace				-	tc	trc
trigger				-	tg	trg
type				-	ty	typ
undo				-	ud	und
user				-	us	usr
view				-	vi	vie
v$view				-	vv	vvi
wait				-	wt	wai
workarea			-	wa	waa

