Rem Script by SRIVENU KADIYALA - mail - srivenu@hotmail.com

activity			-	ac
active				-	av
advise				-	ad
archive				-	ar
area				-	aa
asm				-	as
background			-	bg
big				-	bi
bind				-	bn
block				-	bk
blocking			-	bl
buffer 				-	bu
buffer hashe			-	bh
cache				-	ca
chain				-	ch
child				-	cd
client	 			-	ci
code				-	ce
column				-	cl
compile				-	co
connection			-	cn
constraints			-	ct
costly				-	cs
count				-	cu
cpu				-	cp
cursor				-	cr
datafile			-	df
db				-	db
dead				-	dd
definition			-	de
dependencies			-	dc
destination			-	ds
detail				-	dt
disk				-	dk
dispatcher			-	dp
elapsed				-	el
end				-	en
enqueue				-	eq
event				-	ev
expired				-	ed
extent				-	et
execution			-	ex
explain				-	ep
file				-	fi
find				-	fn
flush				-	fl
format				-	fm
free				-	fr
full				-	fu
function			-	fc
group				-	gr
histograms			-	hg
hit				-	hi
hot				-	ht
id				-	id
indexes				-	in
invalid				-	iv
io				-	io
jdbc				-	jd
job				-	jb
kill				-	ki
large				-	lr
latch				-	la
library				-	li
ln				-	ln
lob				-	lb
lock				-	lk
log				-	lg
long				-	lo
map				-	mp
materialized view		-	mv
memory				-	mm
messages			-	mg
miss				-	ms
mode				-	md
monitor				-	mn
more				-	mo
multi threaded			-	mt
mutex				-	mu
my				-	my
name				-	nm
new				-	ne
object				-	ob
occupants			-	oc
old				-	ol
open				-	oe
operations			-	op
parallel execution		-	px
parameter			-	pm
parse				-	pa
partition			-	pt
pga(memory)			-	py
pin				-	pn
plan				-	pl
pool				-	po
privileges			-	pv
process				-	pr
profile				-	pf
program				-	pg
properties			-	pp
queue				-	qu
rebuild				-	re
recovery			-	rc
redo				-	rd
referential			-	rf
reserved			-	rv
resources			-	rs
role				-	ro
rollback			-	rb
row				-	rw
run				-	ru
segment				-	sg
session 			-	se
sequences			-	sc
shared				-	sr
snapshot 			-	ss
show				-	sh
sid				-	sd
similar				-	si
size				-	sz
sniped				-	sn
sort				-	so
space				-	sp
sql				-	sq
statistics			-	st
summary				-	su
synonyms			-	sm
system 				-	sy
table				-	tb
tablespace			-	ts
temp				-	te
tempfile			-	tf
time				-	tm
transaction			-	tx
trace				-	tc
trigger				-	tg
type				-	ty
undo				-	udst
user				-	us
usage				-	ug
view				-	vi
v$view				-	vv
wait				-	wt
work				-	wk
workarea			-	wa

