Rem Script by SRIVENU KADIYALA - mail - srivenu@hotmail.com
col ksqsttyp  	head "Enqueue" form a10
col descr	head "Description" form a60
col KSQSTSGT  	head  "Gets" form 99,999,999,999
col KSQSTWAT  	head "waits" form 99,999,999,999

SELECT 	ksqsttyp, 
	decode(ksqsttyp,
		'BL','Buffer hash table instance enqueue', 
		'CF','Control file schema global enqueue', 
		'CI','Cross-instance function invocation instance enqueue',
		'CS','Control file schema global enqueue', 
		'CU','Cursor bind enqueue',
		'DF','Data file instance enqueue', 
		'DL','Direct loader parallel index create',
		'DM','Mount/startup db primary/secondary instance enqueue', 
		'DR','Distributed recovery process enqueue', 
		'DV','load a PLSQL object into shared pool enqueue',
		'DX','Distributed transaction entry enqueue', 
		'FB','Formatting a range of Bitmap Benqueues for ASSM enqueue',
		'FI','SGA open-file information enqueue', 
		'FS','File set enqueue', 
		'HW','Space management operations on a specific segment enqueue',
		'IN','Instance number enqueue',
		'IR','Instance recovery serialization global enqueue', 
		'IS','Instance state enqueue',
		'IV','Library cache invalidation instance enqueue', 
		'JD','DBMS Jobs enqueue',
		'JQ','Job queue enqueue',
		'KK','Thread kick enqueue', 
		'MB','Master buffer hash table instance enqueue', 
		'MD','Change Data Capture Materialized View Log enqueue',
		'MM','Mount definition gloabal enqueue', 
		'MR','Media recovery enqueue', 
		'PF','Password file enqueue',
		'PI','Parallel operation enqueue',
		'PR','Process startup enqueue',
		'PS','Parallel operation enqueue',
		'RE','USE_ROW_ENQUEUE enforcement enqueue', 
		'RO','Releasable Objects enqueue (used for truncating tables)',
		'RT','Redo thread global enqueue', 
		'RW','Row wait enqueue', 
		'SC','System commit number instance enqueue', 
		'SH','System commit number high water mark enqueue', 
		'SM','SMON enqueue',
		'SN','Sequence number instance enqueue', 
		'SQ','Sequence number enqueue', 
		'SS','Sort segment enqueue',
		'ST','Space transaction enqueue', 
		'SV','Sequence number value enqueue',
		'SW','Suspend Writes enqueue', 
		'TA','Generic enqueue', 
		'TC','Thread Checkpoint enqueue',
		'TD','DDL enqueue', 
		'TE','Extend-segment enqueue', 
		'TM','DML enqueue', 
		'TO','Temporary Table Object Enqueue', 
		'TS','Temporary segment enqueue', 
		'TT','Temporary table enqueue', 
		'TX','Transaction enqueue', 
		'UL','User supplied enqueue', 
		'UN','User name enqueue', 
		'US','Undo segment DDL enqueue',
		'WL','Being-written redo log instance enqueue', 
		'WS','Write-atomic-log-switch global enqueue',
		'XR','ALTER SYSTEM QUIESCE enqueue') 
	Descr,
	KSQSTSGT, 
	KSQSTWAT
FROM X$KSQST 
where KSQSTWAT>0
order by 3
/