#!/bin/ksh
#set -vx

export rgaccesslog=`ls -t $APACHE_TOP/Apache/logs/access* 2>/dev/null|head -1 ` 2>/dev/null
export ddaccesslog=`ls -t $APACHE_TOP/Apache/logs/cz_access* 2>/dev/null|head -1 ` 2>/dev/null

if [  -f "$rgaccesslog" ] 
then
 echo "=================================="
 echo "Regular Apache Accesses"
 echo "=================================="
 grep -i "$1" $rgaccesslog
fi

if [ ! -f "$ddaccesslog" ] 
then
 exit 1
fi

echo "=================================="
echo "Dedicated Apache Accesses"
echo "=================================="
grep -i "$1" $ddaccesslog